CREATE TABLE IF NOT EXISTS eddy
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    amplitude int2,
    cost_association float4,
    effective_area float4,
    effective_contour_height float4,
    effective_contour_latitude int2,
    effective_contour_longitude int2,
    effective_contour_shape_error int2,
    effective_radius int2,
    inner_contour_height float4,
    latitude float4,
    latitude_max float4,
    longitude float4,
    longitude_max float4,
    num_contours int2,
    num_point_e int2,
    num_point_s int2,
    observation_flag boolean,
    observation_number int2,
    speed_area float4,
    speed_average int4,
    speed_contour_height float4,
    speed_contour_shape geography,
    speed_contour_shape_error int2,
    speed_radius int2,
    date_time timestamp without time zone,
    track int,
    cyclonic_type smallint,
    eddy_point geography(Point,4326) GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography) STORED,
    CONSTRAINT eddy_pkey PRIMARY KEY (track, observation_number, cyclonic_type)
)