networks:
  ocean_network:
    name: ocean_network
    external: true

services:
  postgres_test:
    image: postgis/postgis:16-3.4
    hostname: postgres_test
    container_name: postgres_test
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - ocean_network
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - postgres_data_test:/var/lib/postgresql/data

volumes:
  postgres_data_test:
    name: oceandb_postgres_data_test

