from dataclasses import dataclass
from dataclasses import asdict
import netCDF4 as nc

from typing import List, Tuple, Any, Iterable, Optional
from datetime import datetime, timedelta
from pathlib import Path
from OceanDB.OceanDB_ETL import OceanDBETL


@dataclass
class EddyData:
    id: Optional[int]  # BIGSERIAL identity, generated by DB

    amplitude: Optional[int] = None
    cost_association: Optional[float] = None
    effective_area: Optional[float] = None
    effective_contour_height: Optional[float] = None
    effective_contour_latitude: Optional[int] = None
    effective_contour_longitude: Optional[int] = None
    effective_contour_shape_error: Optional[int] = None
    effective_radius: Optional[int] = None
    inner_contour_height: Optional[float] = None

    latitude: Optional[float] = None
    latitude_max: Optional[float] = None
    longitude: Optional[float] = None
    longitude_max: Optional[float] = None

    num_contours: Optional[int] = None
    num_point_e: Optional[int] = None
    num_point_s: Optional[int] = None

    observation_flag: Optional[bool] = None
    observation_number: Optional[int] = None

    speed_area: Optional[float] = None
    speed_average: Optional[int] = None
    speed_contour_height: Optional[float] = None

    # PostGIS inside Python ORM is usually Any / dict / Shapely geometry
    speed_contour_shape: Optional[Any] = None
    speed_contour_shape_error: Optional[int] = None
    speed_radius: Optional[int] = None

    date_time: Optional[datetime] = None
    track: Optional[int] = None
    cyclonic_type: Optional[int] = None

    # Generated column from longitude/latitude; not user-set
    eddy_point: Optional[Any] = None  # geography(Point,4326)


def extract_data_tuple_from_netcdf(ds: nc.Dataset):
    # Open the NetCDF file
    try:
        # ds = nc.Dataset(file_path, 'r')
        ds.set_auto_mask(False)
        eddy_data = []
        date_time = ds.variables['time']  # Extract dates from the dataset and convert them to standard datetime

        time_data = nc.num2date(date_time[:], date_time.units, only_use_cftime_datetimes=False,
                                only_use_python_datetimes=False)
        ds.set_auto_maskandscale(False)
        eddy_data = {
            'amplitude': ds.variables['amplitude'][:],
            'cost_association': ds.variables['cost_association'][:],
            'effective_area': ds.variables['effective_area'][:],
            'effective_contour_height': ds.variables['effective_contour_height'][:],
            'effective_contour_latitude': ds.variables['effective_contour_latitude'][:],
            'effective_contour_longitude': ds.variables['effective_contour_longitude'][:],
            'effective_contour_shape_error': ds.variables['effective_contour_shape_error'][:],
            'effective_radius': ds.variables['effective_radius'][:],
            'inner_contour_height': ds.variables['inner_contour_height'][:],
            'latitude': ds.variables['latitude'][:],
            'latitude_max': ds.variables['latitude_max'][:],
            'longitude': ds.variables['longitude'][:],
            'longitude_max': ds.variables['longitude_max'][:],
            'num_contours': ds.variables['num_contours'][:],
            'num_point_e': ds.variables['num_point_e'][:],
            'num_point_s': ds.variables['num_point_s'][:],
            'observation_flag': ds.variables['observation_flag'][:],
            'observation_number': ds.variables['observation_number'][:],
            'speed_area': ds.variables['speed_area'][:],
            'speed_average': ds.variables['speed_average'][:],
            'speed_contour_height': ds.variables['speed_contour_height'][:],
            'speed_contour_latitude': ds.variables['speed_contour_latitude'][:],
            'speed_contour_longitude': ds.variables['speed_contour_longitude'][:],
            'speed_contour_shape_error': ds.variables['speed_contour_shape_error'][:],
            'speed_radius': ds.variables['speed_radius'][:],
            'date_time': time_data,
            'track': ds.variables['track'][:],
        }
        ds.close()

        # eddy_data['longitude'][:] = (data['longitude'][:] + 180) % 360 - 180
        return eddy_data
    except Exception as ex:
        print(f"Exception {ex}")
    #     print("File '{}' not found".format(file_path))



filepath = "data/eddy/META3.2_DT_allsat_Anticyclonic_long_19930101_20220209.nc"
cyclonic_filepath = "data/eddy/META3.2_DT_allsat_Cyclonic_long_19930101_20220209.nc"



# extract_data_tuple_from_netcdf(filepath)

oceanadb_etl = OceanDBETL()
cyclonic_ds = oceanadb_etl.load_netcdf(cyclonic_filepath)


oceanadb_etl.load_netcdf(file=Path(filepath))



# ds = oceanadb_etl.load_netcdf(
#     file=Path(filepath)
# )
#
#
# eddy_data = EddyData.from_netcdf(ds)