from dataclasses import dataclass
from datetime import datetime
from typing import Optional, Any

@dataclass
class CheltonEddy:
    id: Optional[int]  # BIGSERIAL identity, generated by DB

    amplitude: Optional[int] = None
    cyclonic_type: Optional[int] = None

    latitude: Optional[float] = None
    longitude: Optional[float] = None

    observation_flag: Optional[bool] = None
    observation_number: Optional[int] = None

    speed_average: Optional[float] = None
    speed_radius: Optional[int] = None

    date_time: Optional[datetime] = None
    track: Optional[int] = None

    # Generated PostGIS point from lon/lat
    chelton_eddy_point: Optional[Any] = None  # geography(Point,4326)

