CREATE TABLE IF NOT EXISTS public.{table_name} (
            file_name text NOT NULL,
            conventions text NULL,
            metadata_conventions text NULL,
            cdm_data_type text NULL,
            comment text NULL,
            contact text NULL,
            creator_email text NULL,
            creator_name text NULL,
            creator_url text NULL,
            date_created timestamp with time zone NULL,
            date_issued timestamp with time zone NULL,
            date_modified timestamp with time zone NULL,
            history text NULL,
            institution text NULL,
            keywords text NULL,
            license text NULL,
            platform text NULL,
            processing_level text NULL,
            product_version text NULL,
            project text NULL,
            "references" text NULL,
            software_version text NULL,
            source text NULL,
            ssalto_duacs_comment text NULL,
            summary text NULL,
            title text NULL,
            CONSTRAINT cop_meta_pkey PRIMARY KEY (nme)
          );