CREATE TABLE IF NOT EXISTS public.{table_name}
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    file_name text COLLATE pg_catalog."default",
    amplitude double precision,
    cost_association real,
    effective_area real,
    effective_contour_height real,
    effective_contour_latitude double precision,
    effective_contour_longitude double precision,
    effective_contour_shape_error double precision,
    effective_radius double precision,
    inner_contour_height real,
    latitude double precision,
    latitude_max double precision,
    longitude double precision,
    longitude_max double precision,
    num_contours smallint,
    num_point_e smallint,
    num_point_s smallint,
    observation_flag boolean,
    observation_number int,
    speed_area real,
    speed_average double precision,
    speed_contour_height real,
    speed_contour_shape geography,
    speed_contour_shape_error double precision,
    speed_radius double precision,
    date_time timestamp without time zone,
    track int,
    cyclonic_type smallint,
    eddy_point geography(Point,4326) GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography) STORED,
    CONSTRAINT eddy_pkey PRIMARY KEY (observation_number, track)
)